### ISSUE TITLE
How should I handle yarn.lock conflicts?

### ISSUE THREAD

**Issue by limonte** [greenkeeperio/greenkeeper-lockfile#110]
The repository I'm asking about: https://github.com/sweetalert2/sweetalert2-adonisjs-nuxtjs

At the same time Greenkeeper submits 2 PRs because 2 dependencies were updated:

- https://github.com/sweetalert2/sweetalert2-adonisjs-nuxtjs/pull/21
- https://github.com/sweetalert2/sweetalert2-adonisjs-nuxtjs/pull/22

If I merge one of them, another will have the `yarn.lock` conflict and I won't be able to merge it. what is the right way to handle such cases?

**Comment by mick352** [comment]
What was your solution?
