### ISSUE TITLE
Merging arbitrary pull requests now?

### ISSUE THREAD

**Issue by simlu** [greenkeeperio/greenkeeper-lockfile#120]
Sorry but WTF. This just merged a completely separate non greenkeeper pr. Anyone got any idea what is going on here?

This was certainly not me, and I doubt it was greenkeeper.
https://github.com/simlu/js-gardener/pull/34

**Comment by travi** [comment]
im not a maintainer of `greenkeeper-lockfile`, but i don't understand what you are trying to raise as an issue against this project. neither `greenkeeper` nor `greenkeeper-lockfile` actually merge any PRs. 

are you possibly using an additional tool like [greenkeeper-keeper](https://github.com/greenkeeper-keeper) (which i do maintain) to actually merge the PR?

**Comment by simlu** [comment]
Apologies. I've opened this issue against the wrong repo. Thank you for pointing this out. I'll reopen as appropriate.
