### ISSUE TITLE
Why does the upload task check for firstPush?

### ISSUE THREAD

**Issue by patkub** [greenkeeperio/greenkeeper-lockfile#136]
Over here, the upload task checks for [firstPush and then uploadBuild](https://github.com/patkub/greenkeeper-lockfile/blob/appveyor-ci-service/upload.js#L35-L41).
But, the update task already checks for [firstPush](https://github.com/patkub/greenkeeper-lockfile/blob/appveyor-ci-service/update.js#L44-L46). Since the upload task runs after the update task, why does the upload task also check firstPush? Is the uploadBuild check not enough?

Removing the firstPush check from the upload task makes it useful in workflows. This would let the user upload the lockfile at the end of a workflow. The firstPush check is needed in the update task so that the lockfile is only updated once, and so that a race condition does not occur in concurrent jobs in a workflow.

This is possibly a better fix for https://github.com/greenkeeperio/greenkeeper-lockfile/pull/118

**Comment by nevir** [comment]
Similarly, the main motivation behind #118 was to be able to upload the lockfile change _only_ if the tests pass (which requires that greenkeeper-lockfile not run as the first task in the workflow)

**Comment by patkub** [comment]
There is a CIRCLE_STAGE=jobname environment variable for the name of the job in the workflow. It defaults to build when not using workflows.
https://circleci.com/docs/2.0/env-vars/

**Comment by nevir** [comment]
> why does the upload task also check firstPush? Is the uploadBuild check not enough?

I think the answer is that we don't want to commit additional lockfile updates if someone pushes more commits to the greenkeeper branch.

The more I dig into this, the more I think #118 (or something that uses git as the source of truth) is actually the right fix:

* We literally only ever want to create a lockfile commit as the second commit on a greenkeeper branch
* The project owner has to be careful, regardless, to not run greenkeeper-lockfile scripts in parallel
* There aren't many great ways of detecting ^ outside of some sort of distributed locking mechanism

**Comment by nevir** [comment]
For now, I'm working around this by _always_ uploading the lockfile during the first workflow step, regardless of the run's success. 

It lets me inspect the exact set of dependencies that caused the error that way, too.

**Comment by patkub** [comment]
We have CIRCLE_JOB, or its alias CIRCLE_STAGE, environment variables for the current job in the workflow. Could we add new environment variables, GK_LOCK_UPDATE_JOB and GK_LOCK_UPLOAD_JOB, to specify the job to update/upload in?

**Comment by patkub** [comment]
You are right, this would just be redundant and not fix the issue. I was trying to re-work the firstPush check because #118 fails with "Only running on first push of a new branch".

**Comment by patkub** [comment]
@nevir Looks like firstPush is going away with monorepos in https://github.com/greenkeeperio/greenkeeper-lockfile/pull/140
