### ISSUE TITLE
"permission denied" errors with CircleCI

### ISSUE THREAD

**Issue by sheelah** [greenkeeperio/greenkeeper-lockfile#153]
I'm getting `/bin/bash: /usr/local/bin/greenkeeper-lockfile-update: Permission denied
Exited with code 1` errors under CircleCI 2.0 during the workflow step where Greenkeeper should be updating `package-lock.json`.

The relevant steps in my build workflow are:
`sudo npm i -g greenkeeper-lockfile@1`: works fine
`greenkeeper-lockfile-update && greenkeeper-lockfile-upload`: permission denied errors

![screen shot 2018-05-16 at 4 58 02 pm](https://user-images.githubusercontent.com/1900318/40148256-5c9d395a-592a-11e8-9f03-9c7bd1b52dbc.jpg)

I verified that `GH_TOKEN` is available in my project's CircleCI environment variables, which is set to a Github personal access token that has full `repo` permissions. Is there something else I need to do to get this working?

Thanks!

**Comment by Xiphe** [comment]
im seeing this, too. It's really flaky though - though it was caused by circle cache but seems to not be the case since you're reinstalling greenkeeper lockfile on every run...

I'll post a failing build once it happens again

**Comment by branoholy** [comment]
I have the same problem but it seems like it's not related to `greenkeeper-lockfile`. The same problem occurs with any package installed globally with `sudo npm i -g`. It's interesting it doesn't happen every time.

**Comment by Xiphe** [comment]
In my case I have `greenkeeper-lockfile` installed as a devDependency of my project and execute it via `$(npm bin)/greenkeeper-lockfile`. No `sudo`, same error

**Comment by Xiphe** [comment]
I also have this error with other npm binaries, so I suspect It's a circle error and not caused by greenkeeper-lockfile

**Comment by sheelah** [comment]
Confirmed I'm also seeing this on a repo that's still using CircleCI 1.0, so it doesn't seem to be limited to CircleCI 2.0 jobs.

**Comment by janl** [comment]
Thanks for reporting. Please reopen this issue, if you see this again, and if you have any pointers as to how greenkeeper-lockfile is involved :)
