### ISSUE TITLE
Example of GK_LOCK_DEFAULT_BRANCH

### ISSUE THREAD

**Issue by albert-olive** [greenkeeperio/greenkeeper-lockfile#170]
Hi,

I don't know where I have to add GK_LOCK_DEFAULT_BRANCH in my CI. Can you provide me an example?

Thanks

**Comment by Realtin** [comment]
That is the branch name against which to make the pull requests to. Very often it is called `master` (then no extra configuration is required). https://github.com/semantic-release/semantic-release for example have a default branch called `caribou`. https://github.com/vuejs/vue have `dev`.
