### ISSUE TITLE
Lockfile update fails on workspace root

### ISSUE THREAD

**Issue by mAAdhaTTah** [greenkeeperio/greenkeeper-lockfile#191]
I have some dev dependencies in my workspace root, which yarn complains about when attempting to add to, which causes greenkeeper to fail. Would it be possible to include the `-W` flag when using yarn in a workspace?

See this build for an example: https://travis-ci.org/valtech-nyc/brookjs/builds/407193342

**Comment by Realtin** [comment]
Could this be set via the `GK_LOCK_YARN_OPTS` Enviroment Variable? https://github.com/greenkeeperio/greenkeeper-lockfile#configuration-options

**Comment by mAAdhaTTah** [comment]
Looks like it. Thanks!
