### ISSUE TITLE
Greenkeeper-lockfile is not uploading updated yarn.lock file

### ISSUE THREAD

**Issue by neu5** [greenkeeperio/greenkeeper-lockfile#193]
Hello,
Greenkeeper created pull request from `greenkeeper/initial` branch:
https://github.com/neu5/zcyklu.pl/pull/59
but it didn't update yarn.lock file because:
`'master' is not a Greenkeeper branch`
Details:
https://travis-ci.org/neu5/zcyklu.pl/jobs/413490472#L504

I don't know if I did something wrong regarding configuration.

**Comment by janl** [comment]
IIRC greenkeeper-lockfile only runs on subsequent, non-initial branches.
