### ISSUE TITLE
Does not update lockfile when monorepo packages are published

### ISSUE THREAD

**Issue by freaktechnik** [greenkeeperio/greenkeeper-lockfile#204]
The lockfile is not updated when multiple packages from a monorepo are updated in a single branch, since it expects there only to be one commit, however there are multiple commits.

Example:
https://github.com/freaktechnik/justintv-stream-notifications/pull/425

**Comment by janl** [comment]
heya @freaktechnik, two options:

1. If you only have public dependencies, Greenkeeper now updates lockfiles automatically:https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0

2. if you have private deps, you still need `greenkeeper-lockfile` to opt into monorepo support, you need to install version 2 explicitly, here:

https://github.com/freaktechnik/justintv-stream-notifications/blob/master/.travis.yml#L25

```
before_install: npm i -g greenkeeper-lockfile@2
```

See https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164 for details.
