### ISSUE TITLE
Lockfile update fails on yarn monorepo

### ISSUE THREAD

**Issue by Alxandr** [greenkeeperio/greenkeeper-lockfile#207]
Updating dependencies in yarn monorepo root requires additional flags to yarn, currently it's failing.
Error:

> error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).

Example build: https://travis-ci.com/YoloDev/rollup-config/builds/83168160#L532

It might be that just always adding `-W` is a good solution.

**Comment by Realtin** [comment]
It should be fixed with the `-W`! 
You can use [GK_LOCK_YARN_OPTS](https://github.com/greenkeeperio/greenkeeper-lockfile#configuration-options) for that. 🌴

**Comment by Alxandr** [comment]
Shouldn't this maybe be default then?
