### ISSUE TITLE
greenkeeper-lockfile-upload fails without descriptive error

### ISSUE THREAD

**Issue by matthewdavidson** [greenkeeperio/greenkeeper-lockfile#209]
Repo: https://github.com/Skyscanner/ensure-node-env
Build log: https://travis-ci.org/Skyscanner/ensure-node-env/builds/422789987#L504

The repo is public so I don't think its an issue related to `GH_TOKEN`.

Any ideas?

**Comment by matthewdavidson** [comment]
Related greenkeeper PR https://github.com/Skyscanner/ensure-node-env/pull/17

**Comment by wolfy1339** [comment]
It seems as if the git push got rejected

**Comment by janl** [comment]
`GH_TOKEN` is still important so `greenkeeper-lockfile` can write the new lockfile back to GitHub.

**Comment by matthewdavidson** [comment]
Thanks @janl, i have added the secret to the repo mentioned above so I'll let you know if the issue remains after the next greenkeeper PR.

**Comment by matthewdavidson** [comment]
After adding `GH_TOKEN` this issue was resolved.
