### ISSUE TITLE
Docs still say to use version 1

### ISSUE THREAD

**Issue by elwayman02** [greenkeeperio/greenkeeper-lockfile#211]
All the examples in the docs reference `greenkeeper-lockfile@1` instead of `greenkeeper-lockfile@2`...is this correct?

**Comment by travi** [comment]
version two hasn't been released to the `latest` channel yet. it still has to be installed using `npm i greenkeeper-lockfile@next`, so i imagine this is the reason that the docs haven't been updated yet

**Comment by elwayman02** [comment]
Ah, are we not supposed to be using v2 yet then?

**Comment by travi** [comment]
i wouldn't say not to use it, but the team is looking for [feedback](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164) about it. personally, i've found it to work well outside of an issue i've found with projects that depend on private packages.

**Comment by janl** [comment]
Yeah, we are still ironing out a few kinks on 2.x. If you have a monorepo, you need 2.x/next, otherwise 1.x works fine.
