### ISSUE TITLE
greenkeeper-lockfile-update fails with Permission denied (publickey).

### ISSUE THREAD

**Issue by prymitive** [greenkeeperio/greenkeeper-lockfile#212]
```
cd ui && greenkeeper-lockfile-update
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
child_process.js:644
    throw err;
    ^
Error: Command failed: git fetch gk-origin
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Full log: https://travis-ci.com/prymitive/karma/jobs/144635477#L453-L482

**Comment by janl** [comment]
Do you have a `GH_TOKEN` set with a valid read/write token to GitHub?

**Comment by prymitive** [comment]
Whole setup was working for me for a while before I started hitting this issue, but it's entirely possible that I rotated a wrong token. Soon after filing this ticket I've seen #214 so I dropp the lockfile stage, so I can't verify this right now. Given that I don't see any other repors of a similiar issue I think we can safely assume that it was my error with the GH_TOKEN, sorry about that.
