### ISSUE TITLE
greenkeeper-lockfile-update exceeding travis max log length

### ISSUE THREAD

**Issue by matthewdavidson** [greenkeeperio/greenkeeper-lockfile#219]
**Repo:** https://github.com/Skyscanner/backpack
**Type:** Monorepo
**`greenkeeper-lockfile` version:** 2.7.1
**Example travis build log:** https://api.travis-ci.org/v3/job/435844871/log.txt

A couple of notable things happening here:

- It seems as if `greenkeeper-lockfile-update` can't find the `package-lock.json` files for the nested packages which is strange because they definately exist:
  ```
  Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
  ```
- `greenkeeper-lockfile-update` is operating on packages located within `node_modules` folders
- The logs generated from the above eventually cause travis to terminate the build

**Comment by matthewdavidson** [comment]
I have just found this issue raised on the repo: https://github.com/Skyscanner/backpack/issues/1077

Is this related?

**Comment by matthewdavidson** [comment]
Given the announcement for "native" lockfile support, do we even need to use `greenkeeper-lockfile` anymore? Skyscanner/backpack is 100% public.

https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0

**Comment by kylemh** [comment]
Have you considered using `npm install --silent`?
