### ISSUE TITLE
CI Reruns after pushing lockfile commit

### ISSUE THREAD

**Issue by john-griffin** [greenkeeperio/greenkeeper-lockfile#24]
After a greenkeeper successful upgrades a dependancy and the lockfile commit is pushed, travis creates new jobs because of the new commit. Is there a way around this as it's effectively testing the same build or is this just a limitation of regenerating the lockfile independently?

**Comment by StephanBijzitter** [comment]
You could test the commit message on your CI, and skip the build based on that. It won't completely skip, but it would be a lot faster as it won't have to install everything and then test everything.

**Comment by boennemann** [comment]
We could think about optionally adding `[ci skip]` to the commit message.
We shouldn't make it a default though, as with GitHub's required status feature you won't be able to merge the Greenkeeper PR w/o the Travis status.

**Comment by john-griffin** [comment]
Would it still work with github required status if it amended the greenkeeper commit with the lockfile and added `[ci skip]` to the message?

**Comment by boennemann** [comment]
No unfortunately not. Also ammending to the first commit makes it way harder to detect "firstPush" on other platforms than Travis CI.

**Comment by janl** [comment]
Closing until somebody comes up with a satisfactory solution
