### ISSUE TITLE
Add Codeship support

### ISSUE THREAD

**Issue by StephanBijzitter** [greenkeeperio/greenkeeper-lockfile#25]
Not sure if this is being worked on already, which is why I'm creating this issue.
Looking at the source, this is what will have to be done:

- [x] An entry must be added to `tests.js` to test for Codeship
https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/ci-services/tests.js

- [x] A file `codeship.js` needs to be created to take the correct environment variables from codeship.
https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/ci-services/travis.js

- [ ] Because Codeship does not provide enough information (for performance reasons), hacky workarounds need to be tested very carefully.

If this is all, I'll be able to do this sometime this week.

**Comment by boennemann** [comment]
Hey @StephanBijzitter,

if you want to tackle this I'm more than happy to assist you with it. You're todo list looks exactly right though :)
I hope the way we implemented the CI service abstraction makes it somewhat easy for your to add this configuration.

Let me know how it goes. Looking forward to your PR 👍 

Best,
Stephan

**Comment by StephanBijzitter** [comment]
Started working on it already! Codeship does not seem to have as much information about pull requests immediately available through [environment variables](https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#default-environment-variables) (as compared to Travis), so I'll have to resort to parsing the result of the command-line.

The way this repository is set up is definitely very nice!

Progress can be seen in my fork, and I'll migrate that pull request to this repository when it's finished.
https://github.com/StephanBijzitter/greenkeeper-lockfile/pull/1

**Comment by teriu** [comment]
Any update on your PR? I see Codeship are still working on the `CI_PULL_REQUEST` var: https://community.codeship.com/t/populate-ci-pull-request/1053

**Comment by StephanBijzitter** [comment]
Yeah it turned out to be more tricky than anticipated, so I moved it to our backlog. Good news though, because I (or someone in my team) will pick this up soon. Of course all help is welcome, but I think we'll able to fit this into the next sprint, or the one after that.

**Comment by selbyk** [comment]
https://github.com/greenkeeperio/greenkeeper-lockfile/pull/72

**Comment by janl** [comment]
Closing in favour of #72

**Comment by ethangj** [comment]
Hey, there - a bit late, but I wanted to let y'all know that we now have this environment variable exposed on Codeship. :)
