### ISSUE TITLE
Update all lockfiles?

### ISSUE THREAD

**Issue by mAAdhaTTah** [greenkeeperio/greenkeeper-lockfile#39]
Right now my project just has a lockfile for yarn, but now that npm@5 is out and uses a lockfile, I'd like to have one for both. Would greenkeeper keep both of them up-to-date, so user could choose which they'd like to use?

**Comment by timbru31** [comment]
I've noticed that yarn is picked instead of package-json.lock, so it seems yarn currently wins.
