### ISSUE TITLE
Updating yarn dependencies fails on travis

### ISSUE THREAD

**Issue by TobiasBales** [greenkeeperio/greenkeeper-lockfile#40]
For us it tries to run `yarn add -S  lint-staged@4.0.0`
lint-staged is a dependency in the project

I think it happens here: https://github.com/greenkeeperio/greenkeeper-lockfile/blob/590bc5fc40dd61d59178fe78f790a61af6c24a7f/lib/update-lockfile.js#L26

But since yarn doesn't accept -S and does that by default it fails

**Comment by valentin-radulescu-hs** [comment]
any update on this?

**Comment by TobiasBales** [comment]
Seems like nobody cares, if I find the time today I will take a stab at it

**Comment by janl** [comment]
Fixed in above linked commits
