### ISSUE TITLE
The authenticity of github.com

### ISSUE THREAD

**Issue by FantasticFiasco** [greenkeeperio/greenkeeper-lockfile#48]
My build on Travis now hang on:

```
$ greenkeeper-lockfile-upload
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```

For reference see my [Travis build](https://travis-ci.org/FantasticFiasco/axis-searchlight/builds/261552850).

**Comment by MaxKalb** [comment]
@FantasticFiasco did you manage to solve this? I have the same problem.

**Comment by FantasticFiasco** [comment]
I think it was a glitch on Travis, after a day or so I triggered a new build and it passed.

Best of lucks!
