### ISSUE TITLE
Make this plugin easily extendable for more CI serv{ers,ices}

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper-lockfile#5]
Right now everything is hardcoded to Travis CI and depending on environment variables set by it.

We should add a mapping for these values, so it's super easy to contribute other CI servers.

**Comment by SpainTrain** [comment]
@boennemann 

open to a PR adding CircleCI?  We use circle extensively and I have personally been champing at the bit for this feature :-)

**Comment by boennemann** [comment]
Hey @SpainTrain,

receiving such a PR would be awesome.

I wanted to work on some sort value mapping, where we define which values we're working with (commit message, branch name, essentially what's `env.TRAVIS*` right now) and a test that determines in which environment we're in (`env.TRAVIS === 'true`).

Then it could be simple to a) contribute config for different CI servers b) only load what's required on runtime.

What do you think about this?
Do you want to await this structure first, or maybe give it a shot yourself?

Best,
Stephan

**Comment by SpainTrain** [comment]
Sure, do you think that it should take a function that returns all the values, or is it a safe assumption that most/all CI services use env vars for all the values we care about?

**Comment by felixfbecker** [comment]
Why not just pass the values as command line arguments? Then you can do eg
```bash
greenkeeper-shrinkwrap-update --branch $CIRCLE_BRANCH
```
