### ISSUE TITLE
"Only running on first push of a new branch" error on new greenkeeper branch

### ISSUE THREAD

**Issue by patkub** [greenkeeperio/greenkeeper-lockfile#50]
I am getting this error for new branches created by greenkeeper. I run greenkeeper-lockfile in CircleCI.
Branch: https://github.com/patkub/rmc1891-site/tree/greenkeeper/bs4-polymer-0.1.12
CircleCI: https://circleci.com/gh/patkub/rmc1891-site/736

Looks like issue #26 still occurs.

**Comment by ethanrubio** [comment]
It looks like this won't work CircleCI's new feature of workflows since the current check is to detect if `CIRCLE_PREVIOUS_BUILD_NUM` exists. Until a better solution is found, I'd recommend placing the greenkeeper updater in the first workflow since subsequent workflows will add `CIRCLE_PREVIOUS_BUILD_NUM`.

**Comment by patkub** [comment]
Still getting the same error after moving the greenkeeper updater to the first job in the workflow.
https://github.com/patkub/rmc1891-site/blob/master/.circleci/config.yml#L232

**Comment by janl** [comment]
@patkub is this still the case and can you point to a current build that shows the behaviour? Thanks!

**Comment by patkub** [comment]
@janl yes this is still the case. I just updated my `bs4-polymer` package to version 0.2.2 which triggered:

- Greenkeeper PR: https://github.com/patkub/rmc1891-site/pull/53
- CircleCI build: https://circleci.com/gh/patkub/rmc1891-site/1293

The `lockfile` job says "Only running on first push of a new branch" for both the `greenkeeper-lockfile-update` and `greenkeeper-lockfile-upload` commands.

CircleCI config: https://github.com/patkub/rmc1891-site/blob/master/.circleci/config.yml

**Comment by ethanrubio** [comment]
@patkub It looks like when you have a workflow that runs the builds in parallel, you run into a race condition issue where whatever build starts first gets `CIRCLE_PREVIOUS_BUILD_NUM=""` (as you can see with this [branch](https://circleci.com/gh/patkub/rmc1891-site/tree/greenkeeper%2Fbs4-polymer-0.2.2) the first build [#1290](https://circleci.com/gh/patkub/rmc1891-site/1290))  while the other builds are given a number. Unfortunately, with the way that the current CirleCI check works, it does not handle this parallel case.

**Comment by patkub** [comment]
@ethanrubio Thank you for explaining the race condition issue. I got this to work by making `lockfile` the first job run and having every other job require `lockfile` to complete before running. This forces the `lockfile` job to run first in the workflow and get `CIRCLE_PREVIOUS_BUILD_NUM=""`. Now the workflow looks like this: https://circleci.com/workflow-run/b5bdf902-65a4-426b-a95a-9429ba96c3a5

**Comment by janl** [comment]
Thanks @ethanrubio & @patkub, we merged the README addition already.
