### ISSUE TITLE
doesn't run as part of the initial: Update dependencies to enable Greenkeeper

### ISSUE THREAD

**Issue by zetaron** [greenkeeperio/greenkeeper-lockfile#60]
We are currently introducing greenkeeper to our projects and the greenkeeper-lockfile tool does not run.

I suspect that this is due to the fact that the `greenekeeper/initial` branch contains the following two commits:
```
chore(package): update dependencies
docs(readme): add Greenkeeper badge
```
But the greenkeeper-lockfile tool expects only one commit.

**Comment by janl** [comment]
Duplicate of https://github.com/greenkeeperio/greenkeeper-lockfile/issues/47
