### ISSUE TITLE
Cannot run with yarn option --ignore-engines

### ISSUE THREAD

**Issue by elenadimitrova** [greenkeeperio/greenkeeper-lockfile#66]
The way we update the lock file currently is using the `--ignore-engines` option as we're using packages on node 4 which require a higher version (e.g. 6.5), one example below
Therefore the `greenkeeper-lockfile-update` command in CI fails with error e.g:
```
error ethjs-abi@0.1.8: The engine "node" is incompatible with this module. Expected version ">=6.5.0".
error Found incompatible module
```

We should be able to pass options to yarn via the `greenkeeper-lockfile-update` script

**Comment by janl** [comment]
Excellent observation! By my estimation, we’d accept a PR that would read a `GK_LOCK_YARN_OPTS` environment variable that then get passed into `yarn` here: https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/lib/update-lockfile.js#L37

Would you be interested in providing a PR?

**Comment by chmanie** [comment]
I took a shot at it here: #78. Feel free to review :)

**Comment by Realtin** [comment]
https://github.com/greenkeeperio/greenkeeper-lockfile/pull/78 is now merged :)
