### ISSUE TITLE
yarn cannot install greenkeeper-lockfile correctly anymore

### ISSUE THREAD

**Issue by danez** [greenkeeperio/greenkeeper-lockfile#98]
As of today the greenkeeper-lockfile binaries are not found anymore by default when installing greenkeeper-lockfile on travis with yarn as described in the README.

I receive this error:

```
greenkeeper-lockfile-update: command not found
```

It might have todo with the latest update of the travis images. https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

Example:
https://travis-ci.org/researchgate/react-fast-highlight/jobs/316007440

I haven't tested with npm.

**Comment by janl** [comment]
thanks, we’ll look into it!

**Comment by genomics-geek** [comment]
Yup - I have the same issue

**Comment by ewolfe** [comment]
@cotsog do you think this problem is on travis-ci's end?

**Comment by cotsog** [comment]
Yes, this is indeed a side effect of the release of your newest Trusty image on Tuesday. Sorry for the inconvenience.

The issue and its workaround is documented here => https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351395853

Here's the snippet to add to your .travis.yml file:

```yaml
before_install:
  - export PATH=$PATH:`yarn global bin`
```

We are currently working on fixing it such that the workaround isn't needed.

Please let me know if this helps to get your builds back on their feet or not.

Cheers!

**Comment by danez** [comment]
This is fixed now and works again.
